name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Verify
        run: |
          dotnet restore
          dotnet format --verify-no-changes --no-restore
          dotnet build --no-restore --configuration Release
          dotnet test --no-build --configuration Release

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
